Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
  config.vm.boot_timeout = 900
  config.vm.hostname = "control-node"  
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.100.10"
  config.vm.synced_folder ".", "/vagrant", type: "nfs" , nfs_export: true
  config.vm.provision "shell", path: "provision.sh"
 
end

end